### ISSUE TITLE
Dependency Tracing does not account for `container.path`

### ISSUE THREAD

**Issue by warrenseymour** [ai-labs-team/casium-devtools#14]
I think that replacing `model` with `pick(container.path, model)` here would solve it, right?

https://github.com/ai-labs-team/casium-devtools/blob/master/dependency-trace.js#L65

A hand-rolled `pick` function will be required as we can't rely on imports within the evaluated function.

**Comment by nateabele** [comment]
Sorry, forgot to reply before. Yeah, that sounds about right.
